language: php

sudo: required

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

services:
  - docker

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssh2-1-dev
  - touch .interactive
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then pecl install -f ssh2-0.13 < .interactive; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then pecl install -f ssh2-1.0 < .interactive; fi
  - php -m | grep ssh2
  - composer self-update
  - composer install
  - composer docker-build
  - composer docker-run
  - eval "$(ssh-agent -s)" #start the ssh agent
  - composer setup-keys
  - ssh-keyscan -p 32768 localhost > tests/_data/knownhosts.file
  - ssh-keygen -l -f tests/_data/knownhosts.file > tests/_data/knownhosts.fp.file
  - cp tests/_data/knownhosts.fp.file ./known_hosts

script:
 - ./vendor/bin/codecept run --env nochecking --env knownhosts --env strictchecking --coverage-xml

after_script:
  - ./vendor/bin/coveralls
