language: php

sudo: required

branches:
  only:
    - master

php:
  - 5.6

services:
  - docker

before_script:
  - docker build -t codecept/secureshell tests/_data/docker/
  - docker run -d -p 127.0.0.1:32768:22 codecept/secureshell
  - docker ps -a
  - apt-get update -qq
  - apt-get install -y -qq libssh2-1-dev libssh2-php
  - touch .interactive
  - pecl install -f ssh2 < .interactive
  - php -m | grep ssh2
  - composer self-update
  - composer install

script:
 - ./vendor/bin/codecept run functional --coverage-xml

after_script:
  - ./vendor/bin/coveralls
