language: php

branches:
  only:
    - master

php:
  - 5.5
  - 5.6

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - php -m | grep ssh2
  - composer self-update
  - composer install

script:
 - ./vendor/bin/codecept run --coverage-xml

after_script:
  - ./vendor/bin/coveralls
