language: php

sudo: required

branches:
  only:
    - master

php:
  - 5.6
  - 7.0

services:
  - docker

before_script:
  - docker build -t codecept/secureshell tests/_data/docker/
  - docker run -d -p 127.0.0.1:32768:22 codecept/secureshell
  - docker ps -a
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libssh2-1-dev
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then sudo apt-get install -y -qq libssh2-php; fi
  - touch .interactive
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then pecl install -f ssh2-1.0 < .interactive; fi
  - php -m | grep ssh2
  - composer self-update
  - composer install

script:
 - ./vendor/bin/codecept run functional --coverage-xml

after_script:
  - ./vendor/bin/coveralls
