language: php

branches:
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - pecl ssh2
  - composer install

script:
 - ./vendor/bin/codecept run --coverage-xml

after_script:
  - ./vendor/bin/coveralls
